version: "3.8"

services:
  db:
    image: postgres:15
    container_name: favorite-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: favorites
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - favorite-net


volumes:
  pgdata:

networks:
  favorite-net:
